#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from orion.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "orion.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tabela.h"

int yylex();          // chamar o analisador léxico
int yyerror(char *s); // impressão de erro e o analisador sintatico para


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_parse_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUM	258
#define	IDENTIFIER	259
#define	BEG	260
#define	BOOLEAN	261
#define	CONST_CHAR	262
#define	CHAR	263
#define	DO	264
#define	END	265
#define	FALSE	266
#define	ENDIF	267
#define	ENDWHILE	268
#define	EXIT	269
#define	INTEGER	270
#define	PROCEDURE	271
#define	PROGRAM	272
#define	REFERENCE	273
#define	REPEAT	274
#define	READ	275
#define	RETURN	276
#define	THEN	277
#define	TRUE	278
#define	TYPE	279
#define	VALUE	280
#define	UNTIL	281
#define	WRITE	282
#define	WHILE	283
#define	ATTRIB	284
#define	DOUBLEDOTS	285
#define	COLON	286
#define	SEMICOLON	287
#define	OPENPAR	288
#define	CLOSEPAR	289
#define	OR	290
#define	AND	291
#define	LE	292
#define	GT	293
#define	EQ	294
#define	LT	295
#define	GE	296
#define	NE	297
#define	NOT	298
#define	PLUS	299
#define	MINUS	300
#define	MULT	301
#define	DIV	302
#define	EXP	303
#define	UMINUS	304
#define	IF	305
#define	ELSE	306


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUM;
static const int IDENTIFIER;
static const int BEG;
static const int BOOLEAN;
static const int CONST_CHAR;
static const int CHAR;
static const int DO;
static const int END;
static const int FALSE;
static const int ENDIF;
static const int ENDWHILE;
static const int EXIT;
static const int INTEGER;
static const int PROCEDURE;
static const int PROGRAM;
static const int REFERENCE;
static const int REPEAT;
static const int READ;
static const int RETURN;
static const int THEN;
static const int TRUE;
static const int TYPE;
static const int VALUE;
static const int UNTIL;
static const int WRITE;
static const int WHILE;
static const int ATTRIB;
static const int DOUBLEDOTS;
static const int COLON;
static const int SEMICOLON;
static const int OPENPAR;
static const int CLOSEPAR;
static const int OR;
static const int AND;
static const int LE;
static const int GT;
static const int EQ;
static const int LT;
static const int GE;
static const int NE;
static const int NOT;
static const int PLUS;
static const int MINUS;
static const int MULT;
static const int DIV;
static const int EXP;
static const int UMINUS;
static const int IF;
static const int ELSE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUM=258
	,IDENTIFIER=259
	,BEG=260
	,BOOLEAN=261
	,CONST_CHAR=262
	,CHAR=263
	,DO=264
	,END=265
	,FALSE=266
	,ENDIF=267
	,ENDWHILE=268
	,EXIT=269
	,INTEGER=270
	,PROCEDURE=271
	,PROGRAM=272
	,REFERENCE=273
	,REPEAT=274
	,READ=275
	,RETURN=276
	,THEN=277
	,TRUE=278
	,TYPE=279
	,VALUE=280
	,UNTIL=281
	,WRITE=282
	,WHILE=283
	,ATTRIB=284
	,DOUBLEDOTS=285
	,COLON=286
	,SEMICOLON=287
	,OPENPAR=288
	,CLOSEPAR=289
	,OR=290
	,AND=291
	,LE=292
	,GT=293
	,EQ=294
	,LT=295
	,GE=296
	,NE=297
	,NOT=298
	,PLUS=299
	,MINUS=300
	,MULT=301
	,DIV=302
	,EXP=303
	,UMINUS=304
	,IF=305
	,ELSE=306


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUM=258;
const int YY_parse_CLASS::IDENTIFIER=259;
const int YY_parse_CLASS::BEG=260;
const int YY_parse_CLASS::BOOLEAN=261;
const int YY_parse_CLASS::CONST_CHAR=262;
const int YY_parse_CLASS::CHAR=263;
const int YY_parse_CLASS::DO=264;
const int YY_parse_CLASS::END=265;
const int YY_parse_CLASS::FALSE=266;
const int YY_parse_CLASS::ENDIF=267;
const int YY_parse_CLASS::ENDWHILE=268;
const int YY_parse_CLASS::EXIT=269;
const int YY_parse_CLASS::INTEGER=270;
const int YY_parse_CLASS::PROCEDURE=271;
const int YY_parse_CLASS::PROGRAM=272;
const int YY_parse_CLASS::REFERENCE=273;
const int YY_parse_CLASS::REPEAT=274;
const int YY_parse_CLASS::READ=275;
const int YY_parse_CLASS::RETURN=276;
const int YY_parse_CLASS::THEN=277;
const int YY_parse_CLASS::TRUE=278;
const int YY_parse_CLASS::TYPE=279;
const int YY_parse_CLASS::VALUE=280;
const int YY_parse_CLASS::UNTIL=281;
const int YY_parse_CLASS::WRITE=282;
const int YY_parse_CLASS::WHILE=283;
const int YY_parse_CLASS::ATTRIB=284;
const int YY_parse_CLASS::DOUBLEDOTS=285;
const int YY_parse_CLASS::COLON=286;
const int YY_parse_CLASS::SEMICOLON=287;
const int YY_parse_CLASS::OPENPAR=288;
const int YY_parse_CLASS::CLOSEPAR=289;
const int YY_parse_CLASS::OR=290;
const int YY_parse_CLASS::AND=291;
const int YY_parse_CLASS::LE=292;
const int YY_parse_CLASS::GT=293;
const int YY_parse_CLASS::EQ=294;
const int YY_parse_CLASS::LT=295;
const int YY_parse_CLASS::GE=296;
const int YY_parse_CLASS::NE=297;
const int YY_parse_CLASS::NOT=298;
const int YY_parse_CLASS::PLUS=299;
const int YY_parse_CLASS::MINUS=300;
const int YY_parse_CLASS::MULT=301;
const int YY_parse_CLASS::DIV=302;
const int YY_parse_CLASS::EXP=303;
const int YY_parse_CLASS::UMINUS=304;
const int YY_parse_CLASS::IF=305;
const int YY_parse_CLASS::ELSE=306;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		184
#define	YYFLAG		-32768
#define	YYNTBASE	57

#define YYTRANSLATE(x) ((unsigned)(x) <= 306 ? yytranslate[x] : 106)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,    52,    50,     2,    51,     2,    53,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    54,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    55,    56
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     8,    13,    18,    20,    22,    24,    26,    30,
    32,    34,    36,    38,    40,    42,    44,    51,    53,    58,
    62,    64,    67,    73,    79,    81,    83,    85,    89,    91,
    93,    95,    97,   102,   104,   106,   108,   110,   115,   117,
   121,   122,   126,   128,   130,   132,   134,   136,   138,   140,
   142,   144,   146,   150,   154,   162,   169,   176,   187,   190,
   193,   196,   199,   201,   203,   205,   208,   210,   212,   216,
   220,   222,   227,   232,   235,   239,   243,   247,   251,   255,
   259,   263,   267,   271,   275,   278,   280,   282,   286,   288,
   290,   292,   294,   296,   298,   300
};

static const short yyrhs[] = {    58,
     0,    17,    66,    60,    64,    59,     0,     5,    81,    64,
    10,     0,    60,    64,    61,    32,     0,    83,     0,    62,
     0,    67,     0,    72,     0,    63,    30,    82,     0,    15,
     0,     6,     0,     8,     0,    71,     0,    83,     0,    83,
     0,    83,     0,    24,    68,    64,    39,    65,    69,     0,
   105,     0,    33,    70,    34,    63,     0,   103,    30,   103,
     0,   105,     0,    73,    74,     0,    77,    16,    64,    80,
    84,     0,    30,    60,    64,    59,    75,     0,    75,     0,
    83,     0,    78,     0,    76,    31,    78,     0,    15,     0,
     6,     0,     8,     0,    83,     0,    79,    63,    30,   105,
     0,    25,     0,    18,     0,   105,     0,    85,     0,    81,
    32,    64,    85,     0,   105,     0,    82,    31,   105,     0,
     0,    33,    76,    34,     0,    83,     0,    86,     0,    87,
     0,    88,     0,    89,     0,    90,     0,    91,     0,    92,
     0,    93,     0,    97,     0,    94,    30,    85,     0,    95,
    29,   100,     0,    28,    64,   100,     9,    64,    81,    13,
     0,    19,    64,    81,    26,    64,   100,     0,    55,   100,
    22,    64,    81,    12,     0,    55,   100,    22,    64,    81,
    65,    56,    64,    81,    12,     0,    20,    95,     0,    27,
   100,     0,    21,   100,     0,    14,   105,     0,   105,     0,
   105,     0,    96,     0,    98,    34,     0,   105,     0,    96,
     0,    99,    33,   100,     0,    98,    31,   100,     0,   105,
     0,   100,    35,    64,   100,     0,   100,    36,    64,   100,
     0,    43,   100,     0,   100,    42,   100,     0,   100,    40,
   100,     0,   100,    38,   100,     0,   100,    41,   100,     0,
   100,    37,   100,     0,   100,    44,   100,     0,   100,    45,
   100,     0,   100,    46,   100,     0,   100,    47,   100,     0,
   100,    48,   100,     0,    45,   100,     0,    95,     0,   101,
     0,    33,   100,    34,     0,   102,     0,   104,     0,   103,
     0,     7,     0,     3,     0,    23,     0,    11,     0,     4,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    68,    71,    74,    77,    78,    81,    82,    83,    86,    89,
    91,    93,    95,    99,   102,   105,   108,   111,   114,   117,
   120,   123,   126,   129,   130,   133,   136,   137,   140,   141,
   142,   143,   146,   149,   150,   153,   156,   157,   160,   161,
   164,   167,   168,   171,   172,   173,   174,   175,   176,   177,
   178,   179,   180,   183,   186,   189,   192,   193,   197,   200,
   203,   206,   209,   212,   213,   216,   219,   220,   223,   224,
   227,   230,   231,   232,   233,   234,   235,   236,   237,   238,
   239,   240,   241,   242,   243,   244,   245,   246,   249,   250,
   253,   254,   257,   260,   261,   264
};

static const char * const yytname[] = {   "$","error","$illegal.","NUM","IDENTIFIER",
"BEG","BOOLEAN","CONST_CHAR","CHAR","DO","END","FALSE","ENDIF","ENDWHILE","EXIT",
"INTEGER","PROCEDURE","PROGRAM","REFERENCE","REPEAT","READ","RETURN","THEN",
"TRUE","TYPE","VALUE","UNTIL","WRITE","WHILE","ATTRIB","DOUBLEDOTS","COLON",
"SEMICOLON","OPENPAR","CLOSEPAR","OR","AND","LE","GT","EQ","LT","GE","NE","NOT",
"PLUS","MINUS","MULT","DIV","EXP","UMINUS","'+'","'-'","'*'","'/'","'='","IF",
"ELSE","CODE","program","bloco","declaracoes","declaracao","decl_de_var","tipo",
"M0","M1","M2","def_de_tipo","nome_do_tipo","definicao_de_tipo","limites","tipo_definido",
"decl_de_proc","proc_cab","pro_corpo","emit_return","lista_de_parametros","tipo_retornado",
"parametro","modo","nome_do_proc","lista_de_comandos","lista_de_ids","vazio",
"espec_de_parametros","comando","comando_de_atribuicao","comando_while","comando_repeat",
"comando_if","comando_read","comando_write","comando_return","comando_exit",
"rotulo","variavel","chamada_ou_indexacao","chamada_de_procedimento","indices",
"variavel2","expr","constante","int_ou_char","inteiro","booleano","identificador",
""
};
#endif

static const short yyr1[] = {     0,
    57,    58,    59,    60,    60,    61,    61,    61,    62,    63,
    63,    63,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    72,    73,    74,    74,    75,    76,    76,    77,    77,
    77,    77,    78,    79,    79,    80,    81,    81,    82,    82,
    83,    84,    84,    85,    85,    85,    85,    85,    85,    85,
    85,    85,    85,    86,    87,    88,    89,    89,    90,    91,
    92,    93,    94,    95,    95,    96,    97,    97,    98,    98,
    99,   100,   100,   100,   100,   100,   100,   100,   100,   100,
   100,   100,   100,   100,   100,   100,   100,   100,   101,   101,
   102,   102,   103,   104,   104,   105
};

static const short yyr2[] = {     0,
     1,     5,     4,     4,     1,     1,     1,     1,     3,     1,
     1,     1,     1,     1,     1,     1,     6,     1,     4,     3,
     1,     2,     5,     5,     1,     1,     1,     3,     1,     1,
     1,     1,     4,     1,     1,     1,     1,     4,     1,     3,
     0,     3,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     3,     3,     7,     6,     6,    10,     2,     2,
     2,     2,     1,     1,     1,     2,     1,     1,     3,     3,
     1,     4,     4,     2,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     2,     1,     1,     3,     1,     1,
     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
    41,     1,    41,    16,    41,     5,    41,    14,    96,     0,
    11,    12,    10,     0,     2,     0,     6,     0,     7,    13,
     8,    41,     0,    32,    21,     0,    41,     0,     0,     0,
    41,     0,    41,    37,    44,    45,    46,    47,    48,    49,
    50,    51,     0,     0,    68,    52,     0,     0,    67,    41,
    18,     4,     0,    41,    22,    25,    26,    41,    62,     0,
    59,    65,    64,    93,    92,    95,    94,     0,     0,     0,
    86,    61,    87,    89,    91,    90,    60,     0,     0,    41,
     0,     0,     0,     0,    66,     0,     0,     9,    39,    41,
     0,     0,     0,    74,    85,    41,    41,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    41,     0,
     3,    53,    54,    70,    69,    41,     0,    41,    41,    36,
    41,    88,     0,     0,    79,    77,    76,    78,    75,    80,
    81,    82,    83,    84,    41,     0,    38,     0,    15,    40,
    41,     0,    43,    23,     0,    72,    73,     0,    41,     0,
    17,    24,    35,    34,     0,    27,     0,    56,     0,    57,
     0,     0,     0,     0,    42,    11,    12,    10,     0,    55,
    41,     0,     0,    28,     0,     0,    19,    20,    33,     0,
    58,     0,     0,     0
};

static const short yydefgoto[] = {   182,
     2,    15,     5,    16,    17,    18,     7,   138,     3,    19,
    50,   151,   162,    20,    21,    22,    55,    56,   155,    23,
   156,   157,   119,    33,    88,     8,   144,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    71,    62,    46,
    47,    48,    72,    73,    74,    75,    76,    63
};

static const short yypact[] = {    18,
-32768,-32768,-32768,-32768,-32768,-32768,    62,-32768,-32768,    10,
    40,    44,    46,     6,-32768,    31,-32768,    39,-32768,-32768,
-32768,    42,    55,-32768,-32768,     6,-32768,     6,   133,   133,
-32768,   133,    47,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    52,    54,    56,-32768,   -13,    66,    28,-32768,
-32768,-32768,     6,-32768,-32768,-32768,-32768,-32768,-32768,    10,
-32768,-32768,    67,-32768,-32768,-32768,-32768,   133,   133,   133,
-32768,   223,-32768,-32768,-32768,-32768,   223,   133,   193,-32768,
    92,    10,   133,   133,-32768,   133,    78,    89,-32768,-32768,
     6,    23,   209,    68,-32768,-32768,-32768,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   176,-32768,    10,
-32768,-32768,   223,   223,   223,-32768,     6,    62,    93,-32768,
-32768,-32768,   133,   133,   150,   257,    50,   115,    68,    61,
    41,     0,    74,    74,-32768,    10,-32768,    95,-32768,-32768,
-32768,    27,-32768,-32768,   133,   236,   248,    10,     4,   122,
-32768,-32768,-32768,-32768,    -8,-32768,    35,   223,    12,-32768,
    75,    98,   104,    27,-32768,-32768,-32768,-32768,   108,-32768,
-32768,    35,   122,-32768,     6,    10,-32768,-32768,-32768,     8,
-32768,   143,   145,-32768
};

static const short yypgoto[] = {-32768,
-32768,    29,    94,-32768,-32768,  -144,   -16,     2,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    11,-32768,-32768,
   -15,-32768,-32768,   -58,-32768,     5,-32768,   -77,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    -6,    -9,-32768,
-32768,-32768,   103,-32768,-32768,  -141,-32768,    -7
};


#define	YYLAST		305


static const short yytable[] = {    25,
    45,    92,    49,    44,   112,     4,    51,     6,   163,     9,
    60,    24,   169,     9,    78,   160,    81,    84,    59,   181,
    85,    61,   164,    26,   170,   165,    57,   177,    27,    28,
    29,   178,   137,    87,     1,    80,    30,    31,     9,    80,
   166,    91,   167,    80,   153,    89,   106,   107,   121,   168,
    45,   154,    49,    44,    80,   -30,   -64,   -63,     6,   -31,
   -71,   -29,    52,   110,    32,     9,    10,    11,    53,    12,
    58,    54,    45,   118,    49,    44,    13,   149,    80,   123,
   124,    82,    83,   120,   -65,    14,   105,   106,   107,   159,
   101,   102,   136,   103,   104,   105,   106,   107,    86,   -71,
    45,   111,    49,    44,   145,   104,   105,   106,   107,   140,
    25,   103,   104,   105,   106,   107,   116,   180,   148,   117,
   139,   107,    24,   143,    64,   142,    45,   150,    49,    44,
   171,   172,    77,   173,    79,    64,     9,   175,    45,    65,
    49,    44,   183,    66,   184,    57,   141,    90,   174,    25,
   161,   152,     0,   139,   176,    67,   102,     0,   103,   104,
   105,   106,   107,     0,    25,    68,    45,   179,    49,    44,
    93,    94,    95,     0,     0,    69,     0,    70,     0,     0,
   108,     0,     0,     0,   135,   113,   114,    99,   115,   100,
   101,   102,     0,   103,   104,   105,   106,   107,     0,     0,
   125,   126,   127,   128,   129,   130,   131,   132,   133,   134,
    96,    97,    98,    99,   109,   100,   101,   102,     0,   103,
   104,   105,   106,   107,     0,   146,   147,    96,    97,    98,
    99,     0,   100,   101,   102,     0,   103,   104,   105,   106,
   107,     0,   122,    96,    97,    98,    99,   158,   100,   101,
   102,     0,   103,   104,   105,   106,   107,    96,    97,    98,
    99,     0,   100,   101,   102,     0,   103,   104,   105,   106,
   107,    97,    98,    99,     0,   100,   101,   102,     0,   103,
   104,   105,   106,   107,    98,    99,     0,   100,   101,   102,
     0,   103,   104,   105,   106,   107,   100,   101,   102,     0,
   103,   104,   105,   106,   107
};

static const short yycheck[] = {     7,
    10,    60,    10,    10,    82,     1,    14,     3,   150,     4,
    27,     7,   157,     4,    31,    12,    33,    31,    26,    12,
    34,    28,    31,    14,    13,    34,    22,   172,    19,    20,
    21,   173,   110,    50,    17,    32,    27,    28,     4,    32,
     6,    58,     8,    32,    18,    53,    47,    48,    26,    15,
    60,    25,    60,    60,    32,    16,    29,    30,    54,    16,
    33,    16,    32,    80,    55,     4,     5,     6,    30,     8,
    16,    30,    82,    90,    82,    82,    15,   136,    32,    96,
    97,    30,    29,    91,    29,    24,    46,    47,    48,   148,
    41,    42,   109,    44,    45,    46,    47,    48,    33,    33,
   110,    10,   110,   110,   121,    45,    46,    47,    48,   117,
   118,    44,    45,    46,    47,    48,    39,   176,   135,    31,
   116,    48,   118,   119,     3,    33,   136,    33,   136,   136,
    56,    34,    30,    30,    32,     3,     4,    30,   148,     7,
   148,   148,     0,    11,     0,   141,   118,    54,   164,   157,
   149,   141,    -1,   149,   171,    23,    42,    -1,    44,    45,
    46,    47,    48,    -1,   172,    33,   176,   175,   176,   176,
    68,    69,    70,    -1,    -1,    43,    -1,    45,    -1,    -1,
    78,    -1,    -1,    -1,     9,    83,    84,    38,    86,    40,
    41,    42,    -1,    44,    45,    46,    47,    48,    -1,    -1,
    98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
    35,    36,    37,    38,    22,    40,    41,    42,    -1,    44,
    45,    46,    47,    48,    -1,   123,   124,    35,    36,    37,
    38,    -1,    40,    41,    42,    -1,    44,    45,    46,    47,
    48,    -1,    34,    35,    36,    37,    38,   145,    40,    41,
    42,    -1,    44,    45,    46,    47,    48,    35,    36,    37,
    38,    -1,    40,    41,    42,    -1,    44,    45,    46,    47,
    48,    36,    37,    38,    -1,    40,    41,    42,    -1,    44,
    45,    46,    47,    48,    37,    38,    -1,    40,    41,    42,
    -1,    44,    45,    46,    47,    48,    40,    41,    42,    -1,
    44,    45,    46,    47,    48
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 10:
#line 89 "orion.y"
{ // tipo 0
                ;
    break;}
case 11:
#line 91 "orion.y"
{ // tipo 1
                ;
    break;}
case 12:
#line 93 "orion.y"
{ // tipo 2
                ;
    break;}
case 13:
#line 95 "orion.y"
{ // tipo 3
                ;
    break;}
case 96:
#line 264 "orion.y"
{instalarNaTS();;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 267 "orion.y"


extern int line_num;
extern void lexemefoundErroSintatico();
extern FILE *saida;
extern simbolo_t tabela_simbolos[TAB_SIZE];


int main(int argc, char* argv[]){	
	if(argc != 2){
		printf("Maneira correta de se usar o analisador sintatico: ./a.out arquivo_teste\n");
		exit(1);
	}
		
	yyin = fopen(argv[1], "r"); // para leitura do arquivo com código fonte
	if(yyin == NULL){
		printf("Arquivo nao encontrado.\n");
		return 1;
	}

	// arquivo de saida com o programa fonte
	saida = fopen("saida.txt", "w");
	
	// Iniciar numeração do programa fonte no arquivo e no terminal, com valor 1
	fprintf(saida, "%d ", line_num);
	printf("%d ", line_num);

	// iniciar TS
	iniciaListaNO();

	// Executar o analisador sintático, retorna 0 quando o programa está correto
	if(!yyparse()){
		 printf("\n\n***** Programa sintaticamente correto! *****\n");
	}
	
	printf("\n");

	// Imprime a tabela de simbolos
	Imprime_Tabela();

	fclose(saida);
	return 0;
}

int yyerror(char *s) {
	printf("\n\n***** Erro sintatico na linha %d ou %d, verificar na vizinhanca do token: ", line_num - 1, line_num);
	fprintf(saida, "\n\n***** Erro sintatico na linha %d ou %d, verificar na vizinhanca do token: ", line_num - 1, line_num);
	lexemefoundErroSintatico();
}	

